In [ ]:
import numpy as np
np.arange(-4, -15, -2)

In [ ]:
from scipy.constants import h, c, k, pi, Wien
import numpy as np
import sympy as smp

T = 1000
l, C = smp.symbols('\lambda c')

I = l**(-5) / (smp.exp(C / l) - 1)
Wien

In [ ]:
from astropy.constants import G, M_earth

In [ ]:
import sympy as smp

A = smp.Matrix([[0, -1], [0, 0]])
abs(A)

In [ ]:
import numpy as np

A = np.identity(2)
v = np.matrix(np.array([1, 1]))
((A * v.T).T)[0]

In [ ]:
import numpy as np

B = np.zeros((2, 2))

In [ ]:
np.round(A * B, 3)

In [ ]:
from Import_Modules.Newton_Multivar import Newton_MultiVar
import sympy as smp
import numpy as np

x, y = smp.symbols('x y')
F = [y**2 * (1 - x) - x**3, y**2 + x**2 - 1]
x_0 = np.array([1, 1])

Newton_MultiVar([x, y], F, x_0, 10**(-6), N_max = 200, print_out = True, TOL_Parameter = 'Absolute')

In [2]:
import numpy as np

b = np.array([1, 1, 1])
b[2] = b[2] - 1
b


array([1, 1, 0])

In [7]:
import numpy as np
x = np.array([1j, 1j, 1j])
(np.array([x, x, x]))

array([[0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j]])

In [5]:
x = y = 2
x = x + 2
y

2

In [8]:
from cmath import phase

phase(1j)

1.5707963267948966

In [6]:
for i in range(4, 3):
    print(i)

In [9]:
import numpy as np

A = np.zeros((4, 4))
A[3, 1] = 1
A[-1, -3]

1.0

In [10]:
import numpy as np

np.zeros(3)

array([0., 0., 0.])

In [ ]:
import numpy as np
from Problem_14_Another_Circuit.Problem_14 import A_gen
A = A_gen(5)
Q, R = np.linalg.qr(A)
Q*R